# Use Ubuntu as the base image
FROM ubuntu:latest

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/root
ENV APP_HOME=$HOME/cpp
WORKDIR $APP_HOME

# Update the package list
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common wget gnupg

# Install clang-17
RUN wget https://apt.llvm.org/llvm.sh \
    && chmod +x llvm.sh \
    && echo | ./llvm.sh 17 \
    && ln -sf /usr/bin/clang-17 /usr/bin/clang \
    && ln -sf /usr/bin/clang++-17 /usr/bin/clang++

# Install cmake
RUN wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-linux-aarch64.sh \
    && chmod +x cmake.sh \
    && ./cmake.sh --skip-license --prefix=/usr/local \
    && rm cmake.sh


# Install build-essential and the LLVM toolchain
RUN apt-get install -y \
    build-essential \
    linux-libc-dev \
    git \
    libboost-all-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libgtest-dev \
    pkg-config \
    curl \
    doxygen \
    graphviz \
    vim

# Clean up the apt cache to reduce image size
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p $APP_HOME/build

COPY . $APP_HOME

# Reset the frontend to its original state
ENV DEBIAN_FRONTEND=

# Set the default command to bash
CMD ["bash"]
